name: "dia_proteomics_analysis"
description: |
  Complete DIA-NN proteomics analysis pipeline including in-silico library generation,
  preliminary analysis, empirical library assembly, individual analysis, and final quantification.
  This subworkflow combines DIA-NN modules with quantms-utils for comprehensive
  data-independent acquisition (DIA) proteomics data processing.
keywords:
  - diann
  - proteomics
  - dia
  - quantification
  - spectral library
  - quantms-utils
tools:
  - "diann":
      description: |
        DIA-NN is a universal software for data-independent acquisition (DIA) proteomics data processing.
        It uses deep learning to predict spectral libraries and perform peptide identification and quantification.
      homepage: "https://github.com/vdemichev/DiaNN"
      documentation: "https://github.com/vdemichev/DiaNN"
      tool_dev_url: "https://github.com/vdemichev/DiaNN"
      doi: "10.1038/s41592-020-01009-0"
      licence: ["https://github.com/vdemichev/DiaNN/blob/1.8.1/LICENSE.txt"]
      identifier: "biotools:diann"
  - "quantms-utils":
      description: |
        quantms-utils is a Python package with scripts and functions for quantitative proteomics data analysis.
        The dianncfg command converts enzyme and modification parameters to DIA-NN-compatible format.
      homepage: "https://github.com/bigbio/quantms-utils"
      documentation: "https://github.com/bigbio/quantms-utils"
      tool_dev_url: "https://github.com/bigbio/quantms-utils"
      licence: ["MIT"]
      identifier: "biotools:quantms-utils"
input:
  - - ch_ms_files:
        type: channel
        description: |
          Channel containing tuples of meta maps and mass spectrometry files
          e.g. `[[id:'sample1'], file('sample1.mzML')]`
        pattern: "*.{mzML,mzml}"
    - ch_fasta:
        type: channel
        description: |
          Channel containing tuples of meta maps and protein sequence database in FASTA format
          e.g. `[[id:'sample1'], file('database.fasta')]`
        pattern: "*.{fasta,fa}"
    - ch_enzyme_mods:
        type: channel
        description: |
          Channel containing tuples of meta map, enzyme, fixed modifications, and variable modifications
          e.g. `[[id:'sample1'], 'Trypsin', 'Carbamidomethyl (C)', 'Oxidation (M)']`
output:
  versions:
    - versions.yml:
        type: file
        description: File containing software versions
        pattern: "versions.yml"
        ontologies:
          - edam: http://edamontology.org/format_3750 # YAML
  diann_report:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tsv":
          type: file
          description: Main DIA-NN report in TSV format
          pattern: "*.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV format
  diann_report_parquet:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.parquet":
          type: file
          description: Main DIA-NN report in Parquet format
          pattern: "*.parquet"
          ontologies:
            - edam: http://edamontology.org/format_3750 # Parquet format
  diann_report_stats:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.stats.tsv":
          type: file
          description: DIA-NN report statistics
          pattern: "*.stats.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV format
  pr_matrix:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.pr_matrix.tsv":
          type: file
          description: Peptide-to-run matrix
          pattern: "*.pr_matrix.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV format
  pg_matrix:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.pg_matrix.tsv":
          type: file
          description: Protein group matrix
          pattern: "*.pg_matrix.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV format
  gg_matrix:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.gg_matrix.tsv":
          type: file
          description: Gene group matrix
          pattern: "*.gg_matrix.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV format
  unique_gene_matrix:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.unique_genes_matrix.tsv":
          type: file
          description: Unique genes matrix
          pattern: "*.unique_genes_matrix.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3475 # TSV format
  empirical_library:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.tsv":
          type: file
          description: Final empirical spectral library
          pattern: "*.tsv"
          ontologies:
            - edam: http://edamontology.org/format_3240 # Spectral library format
  log:
    - - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
      - "*.log":
          type: file
          description: DIA-NN log file
          pattern: "*.log"
          ontologies:
            - edam: http://edamontology.org/format_2330 # Text format
authors:
  - "@daichengxin"
  - "@pinin4fjords"
maintainers:
  - "@daichengxin"
