# yaml-language-server: $schema=https://raw.githubusercontent.com/nf-core/modules/master/modules/meta-schema.json
name: fastcov
description: generate a coverage plot from one or more bam files
keywords:
  - coverage
  - bam
  - map
tools:
  - fastcov:
      description: "generate a coverage plot from one or more bam files"
      homepage: "https://github.com/RaverJay/fastcov/"
      documentation: "https://github.com/RaverJay/fastcov/blob/main/README.md"
      tool_dev_url: "https://github.com/RaverJay/fastcov/tree/main"
      licence: ["MIT"]
      identifier: ""

input:
  # Only when we have meta
  - - meta:
        type: map
        description: |
          Groovy Map containing sample information
          e.g. `[ id:'sample1' ]`
    - bam:
        type: file
        description: BAM file
        pattern: "*.bam"
    - index:
        type: file
        description: BAM index file
        pattern: "*.bai"
    - file_ext:
        type: string
        description: output plot file extension string
    - args:
        type: string
        description: additional fastcov arguments string

output:
  #Only when we have meta
  - coverage_plot:
      - meta:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
          pattern: "*.{png,svg,pdf}"
      - ${prefix}.${file_ext}:
          type: map
          description: |
            Groovy Map containing sample information
            e.g. `[ id:'sample1' ]`
          pattern: "*.{png,svg,pdf}"
  - versions:
      - versions.yml:
          type: file
          description: File containing software versions
          pattern: "versions.yml"
authors:
  - "@davidfischer"
maintainers:
  - "@davidfischer"
