name: "MSSTATS_MSSTATSLFQ"
description: "Statistical analysis of label-free quantification data using MSstats"
keywords:
  - "msstats"
  - "statistics"
  - "proteomics"
  - "label-free"
  - "quantification"
tools:
  - "msstats":
      description: "MSstats is an R package for statistical analysis of quantitative proteomics data"
      homepage: "https://github.com/MeenaChoi/MSstats"
      documentation: "https://msstats.org/"
      tool_dev_url: "https://github.com/MeenaChoi/MSstats"
      doi: "10.1021/acs.jproteome.0c00063"
      licence: "['Artistic-2.0']"
input:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', name:'test', condition:'test' ]
  - msstats_csv_input:
      type: file
      description: "MSstats input CSV file"
      pattern: "*.csv"
output:
  - meta:
      type: map
      description: |
        Groovy Map containing sample information
        e.g. [ id:'test', name:'test', condition:'test' ]
  - versions:
      type: file
      description: "File containing software versions"
      pattern: "versions.yml"
  - msstats_csv:
      type: file
      description: "MSstats results CSV file"
      pattern: "*.csv"
  - log:
      type: file
      description: "Log file"
      pattern: "*.log"
  - pdf:
      type: file
      description: "PDF plots (optional)"
      pattern: "*.pdf"
authors:
  - "@bigbio"
  - "@nf-core"
